<a href="https://colab.research.google.com/github/vijayakrishna92/machine-learning/blob/main/dataset002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

## import dataset

In [2]:
var = pd.read_csv('Data.csv')
X = var.iloc[:,:-1].values # reading all rows and first 3 column datas
#print(X) # iloc and values are from pandas
y =var.iloc[:,-1].values # reading all rows and last column datas
#print(y)

In [3]:
m_val = SimpleImputer(missing_values=np.nan, strategy='mean')
m_val.fit(X[:,1:3])
X[:,1:3] = m_val.transform(X[:,1:3])
#print(X)

## encoding

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
print(X)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 38.77777777777778 52000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


##splitting dataset into training set and test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 1)

In [8]:
print(X_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [9]:
print(X_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


In [10]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [11]:
print(y_test)

[0 1]


## Feature scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,8:] = sc.fit_transform(X_train[:,8:])
X_test[:,8:] = sc.transform(X_test[:,8:])

In [14]:
print(X_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 -0.19159184384578545
  -1.0781259408412425]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.014117293757057777
  -0.07013167641635372]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 -0.30453019390224867
  -0.30786617274297867]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.9018011447007988 -1.420463615551582]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [15]:
print(X_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
